language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn run build
on:
  branch: master
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP